package exception_throws;public class MainTest {
}
